name: Download and Commit JSON

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Isotoma executable
        run: |
          curl -L -o Isotoma https://github.com/tokizuoh/Isotoma/releases/download/1.0/Isotoma
          chmod +x Isotoma

      - name: Run Isotoma executable
        run: |
          ./Isotoma
          mv latest_posts.json src/data/

      - name: Configure git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit generated JSON
        run: |
          git add latest_posts.json
          git commit -m "Add generated JSON files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
